<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function custom_formatter_preprocess_field(&$variables) {
  // "field_image" field in the article content type (and not elsewhere)
  if ($variables['element']['#field_name'] != 'field_image') {
    return;
  }

  if ($variables['element']['#entity_type'] == 'node' && $variables['element']['#bundle'] == 'article') {
    // Display the title of the node to which the image belongs
    // @see field--node--field-image--article.html.twig
    $entity = $variables['element']['#object'];
    $variables['entity_title'] = $entity->get('title')->getValue()[0]['value'];
  }
}
